# Generated by Django 3.2 on 2022-04-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records_feed', '0004_setter_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setter',
            name='country',
        ),
    ]
