# Generated by Django 3.2 on 2022-04-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records_feed', '0005_auto_20220411_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_organiser',
            field=models.BooleanField(default=True),
        ),
    ]
