# Generated by Django 3.2 on 2022-04-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records_feed', '0006_setter_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setter',
            name='country',
        ),
    ]
