# Generated by Django 3.2 on 2022-04-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records_feed', '0007_remove_setter_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setter',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
