# Generated by Django 3.2 on 2022-04-14 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records_feed', '0007_rename_profile_agent_organiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='setter',
            name='organiser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records_feed.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setter',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records_feed.agent'),
        ),
    ]
